name: github-action
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          TEST: ${{ secrets.TEST_SECRET }}
      - run: sh ./scripts/test.sh
